### ISSUE TITLE
Docs Migration - Minor updates

### ISSUE THREAD

**Issue by Krish1979** [ConsenSys/doc.goquorum#11]
- [ ] ConsenSys/quorum#1040 - The pages documenting usage of the Hashicorp Vault plugin docs are not migrated over.
- [x] https://docs.goquorum.consensys.net/en/latest/HowTo/ManageKeys/AccountPlugins/#example - Heading level needs fixing to be consistent
- [x] https://docs.goquorum.consensys.net/en/latest/Concepts/Privacy/ContractExtension/#note - Formatting of first element in list is broken. Needs a line spacing (this is also carried over from previous documentation)
- [x] https://docs.goquorum.consensys.net/en/latest/Concepts/Plugins/PluginsArchitecture/#plugin-reloading - link to “HelloWorld plugin example” is not correct. It should be `Concepts/Plugins/Plugins/#example-helloworld-plugin
Tessera`
- [x] Logging documentation PR ConsenSys/quorum#1013 - Could you created under relevant  section and original PR closed.

Once above documentation updates are completed along with ConsenSys/doc.tessera#9, PR ConsenSys/quorum#1062 to delete old documentation could be actioned.

**Comment by NicolasMassart** [comment]
ConsenSys/quorum#1013 will be recreated by the contributor on the new repos
