### ISSUE TITLE
search: "consensus" unexpected behaviour

### ISSUE THREAD

**Issue by macfarla** [ConsenSys/doc.goquorum#184]
On this page
https://consensys.net/docs/goquorum/en/latest/
using search 
searching for "consensus" I start typing
search for "consensu" 27 results
![Screen Shot 2022-01-18 at 7 54 31 am](https://user-images.githubusercontent.com/2627919/149841107-4e3dfd5d-eb94-4f5d-b387-46557b08003a.png)

search for "consensus" 0 results
![Screen Shot 2022-01-18 at 7 54 40 am](https://user-images.githubusercontent.com/2627919/149841123-a743495d-b3f0-4af1-a7bc-2d9d7d9d1c8c.png)

**Comment by NicolasMassart** [comment]
This issue happens also on other doc, not goquorum related so to be fixed in https://github.com/Consensys/doctools.template-site/
